name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Build Docs
        run: |
          mkdocs build
      
      - name: 'Compress Zip'
        run: |
          zip -r "manpi_release_${{ env.GITHUB_REF }}.zip" \
          site/ \
      
      - name: Restore qshell from cache
        uses: actions/cache@v4
        with:
          path: qshell
          key: qshell-${{ runner.os }}-v2.13.0
          
      - name: Check if qshell is cached
        run: |
          if [ -d "qshell" ]; then
            echo "qshell is cached"
          else
            echo "qshell is not cached"
            wget -O qshell.tar.gz https://github.com/qiniu/qshell/releases/download/v2.13.0/qshell-v2.13.0-linux-amd64.tar.gz
            mkdir -p qshell
            tar -xzf qshell.tar.gz -C qshell --strip-components=1
          fi

      - name: Print workspace path
        run: |
          echo "Workspace path: ${{ github.workspace }}"

      - name: Run qshell command
        run: |
          ./qshell/qshell account ${{  secrets.CI_CDN_ACCESS_KEY }} ${{ secrets.CI_CDN_SECRET_KEY }} manpi
          ./qshell/qshell qupload2 --src-dir=${{ github.workspace }}/site --bucket=${{ secrets.CI_CDN_BUCKET }}
      
      - name: 'Upload Release'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: ${{ github.workspace }}/docs/about/changelog.md
          files: |
            manpi_release_${{ env.GITHUB_REF }}.zip
        